Inpute datasets

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
import pandas as pd

# Change this path ONLY if your folder name is different
base_path = "/content/drive/MyDrive/2179code/"

In [8]:
train_df = pd.read_csv(base_path + "train_data.csv")
test_df  = pd.read_csv(base_path + "test_data.csv")

In [9]:
print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

train_df.head()

Train shape: (18788, 10)
Test shape: (4698, 10)

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,1092,31,Versatile,I passed over this dress online thinking i'd n...,5,1,0,General,Dresses,Dresses
1,406,33,"Such a unique, flattering swimsuit!",I am so excited about this swimsuit. i have ne...,5,1,0,Initmates,Intimate,Swim
2,1008,31,"The perfect skirt for all year, every year.","To start: i'm 135 lbs, 5'7"", 34c, 28 jeans, si...",5,1,0,General Petite,Bottoms,Skirts
3,836,59,Love this blouse,I really like this blouse a lot. very very eas...,5,1,0,General,Tops,Blouses
4,1030,39,So crazy comfortable,I haven't worn jeans in a year because i felt ...,5,1,0,General,Bottoms,Jeans

Data clean and validation

In [43]:
# =========================
# 1. INITIAL INSPECTION
# =========================

print("=== TRAIN INFO ===")
train_df.info()

print("\n=== TEST INFO ===")
test_df.info()

print("\n=== MISSING VALUES (TRAIN) ===")
print(train_df.isnull().sum())

print("\n=== MISSING VALUES (TEST) ===")
print(test_df.isnull().sum())

print("\n=== TRAIN HEAD ===")
display(train_df.head())

print("\n=== TEST HEAD ===")
display(test_df.head())

=== TRAIN INFO ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18788 entries, 0 to 18787
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Clothing ID              18788 non-null  int64
 1   Age                      18788 non-null  int64
 2   Title                    18788 non-null  object
 3   Review Text              18788 non-null  object
 4   Rating                   18788 non-null  int64
 5   Recommended IND          18788 non-null  int64
 6   Positive Feedback Count  18788 non-null  int64
 7   Division Name            18776 non-null  object
 8   Department Name          18776 non-null  object
 9   Class Name               18776 non-null  object
 10  text_combined            18788 non-null  object
 11  text_clean               18788 non-null  object
dtypes: int64(5), object(7)
memory usage: 1.7+ MB

=== TEST INFO ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4698 entries, 0 to 4697
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Clothing ID              4698 non-null   int64
 1   Age                      4698 non-null   int64
 2   Title                    4698 non-null   object
 3   Review Text              4698 non-null   object
 4   Rating                   4698 non-null   int64
 5   Recommended IND          4698 non-null   int64
 6   Positive Feedback Count  4698 non-null   int64
 7   Division Name            4696 non-null   object
 8   Department Name          4696 non-null   object
 9   Class Name               4696 non-null   object
 10  text_combined            4698 non-null   object
 11  text_clean               4698 non-null   object
dtypes: int64(5), object(7)
memory usage: 440.6+ KB

=== MISSING VALUES (TRAIN) ===
Clothing ID                 0
Age                         0
Title                       0
Review Text                 0
Rating                      0
Recommended IND             0
Positive Feedback Count     0
Division Name              12
Department Name            12
Class Name                 12
text_combined               0
text_clean                  0
dtype: int64

=== MISSING VALUES (TEST) ===
Clothing ID                0
Age                        0
Title                      0
Review Text                0
Rating                     0
Recommended IND            0
Positive Feedback Count    0
Division Name              2
Department Name            2
Class Name                 2
text_combined              0
text_clean                 0
dtype: int64

=== TRAIN HEAD ===

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,text_combined,text_clean
0,1092,31,Versatile,I passed over this dress online thinking i'd n...,5,1,0,General,Dresses,Dresses,Versatile I passed over this dress online thin...,versatile i passed over this dress online thin...
1,406,33,"Such a unique, flattering swimsuit!",I am so excited about this swimsuit. i have ne...,5,1,0,Initmates,Intimate,Swim,"Such a unique, flattering swimsuit! I am so ex...",such a unique flattering swimsuit i am so exci...
2,1008,31,"The perfect skirt for all year, every year.","To start: i'm 135 lbs, 5'7"", 34c, 28 jeans, si...",5,1,0,General Petite,Bottoms,Skirts,"The perfect skirt for all year, every year. To...",the perfect skirt for all year every year to s...
3,836,59,Love this blouse,I really like this blouse a lot. very very eas...,5,1,0,General,Tops,Blouses,Love this blouse I really like this blouse a l...,love this blouse i really like this blouse a l...
4,1030,39,So crazy comfortable,I haven't worn jeans in a year because i felt ...,5,1,0,General,Bottoms,Jeans,So crazy comfortable I haven't worn jeans in a...,so crazy comfortable i havent worn jeans in a ...

=== TEST HEAD ===

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,text_combined,text_clean
0,1095,34,Size up if busty,I agree with the other reviewer that the color...,4,1,19,General,Dresses,Dresses,Size up if busty I agree with the other review...,size up if busty i agree with the other review...
1,903,57,Snap front hoodie,I have many sweaters but i bought this during ...,4,1,0,General Petite,Tops,Fine gauge,Snap front hoodie I have many sweaters but i b...,snap front hoodie i have many sweaters but i b...
2,830,56,Adorable,Beautiful top but runs a whole size small. gav...,4,1,3,General,Tops,Blouses,Adorable Beautiful top but runs a whole size s...,adorable beautiful top but runs a whole size s...
3,1047,36,Fraying after 2 wears!,I loved these pants.they are so comfortable. h...,3,0,3,General Petite,Bottoms,Pants,Fraying after 2 wears! I loved these pants.the...,fraying after wears i loved these pantsthey ar...
4,1110,30,Fabulous material....,I ordered this dress in a petite but it arrive...,5,1,0,General,Dresses,Dresses,Fabulous material.... I ordered this dress in ...,fabulous material i ordered this dress in a pe...

In [44]:
# =========================
# 2. COLUMN CHECK + TARGET VALIDATION
# =========================

print("Train columns:")
print(train_df.columns.tolist())

print("\nTest columns:")
print(test_df.columns.tolist())

print("\nRecommended IND distribution:")
print(train_df['Recommended IND'].value_counts(dropna=False))

print("\nRating distribution:")
print(train_df['Rating'].value_counts(dropna=False))

Train columns:
['Clothing ID', 'Age', 'Title', 'Review Text', 'Rating', 'Recommended IND', 'Positive Feedback Count', 'Division Name', 'Department Name', 'Class Name', 'text_combined', 'text_clean']

Test columns:
['Clothing ID', 'Age', 'Title', 'Review Text', 'Rating', 'Recommended IND', 'Positive Feedback Count', 'Division Name', 'Department Name', 'Class Name', 'text_combined', 'text_clean']

Recommended IND distribution:
Recommended IND
1    15467
0     3321
Name: count, dtype: int64

Rating distribution:
Rating
5    10540
4     4060
3     2251
2     1248
1      689
Name: count, dtype: int64

In [45]:
# =========================
# 3. HANDLE MISSING VALUES
# =========================

import pandas as pd
import numpy as np

# text columns commonly used in this dataset
text_cols = ['Title', 'Review Text']

for col in text_cols:
    if col in train_df.columns:
        train_df[col] = train_df[col].fillna("")
    if col in test_df.columns:
        test_df[col] = test_df[col].fillna("")

# fill numeric columns using training medians
numeric_cols = train_df.select_dtypes(include=['int64', 'float64']).columns.tolist()

for col in numeric_cols:
    median_value = train_df[col].median()
    train_df[col] = train_df[col].fillna(median_value)
    if col in test_df.columns:
        test_df[col] = test_df[col].fillna(median_value)

print("Remaining missing values in TRAIN:")
print(train_df.isnull().sum())

print("\nRemaining missing values in TEST:")
print(test_df.isnull().sum())

Remaining missing values in TRAIN:
Clothing ID                 0
Age                         0
Title                       0
Review Text                 0
Rating                      0
Recommended IND             0
Positive Feedback Count     0
Division Name              12
Department Name            12
Class Name                 12
text_combined               0
text_clean                  0
dtype: int64

Remaining missing values in TEST:
Clothing ID                0
Age                        0
Title                      0
Review Text                0
Rating                     0
Recommended IND            0
Positive Feedback Count    0
Division Name              2
Department Name            2
Class Name                 2
text_combined              0
text_clean                 0
dtype: int64

In [46]:
# =========================
# 4. CREATE TEXT FEATURE
# =========================

train_df['text_combined'] = train_df['Title'].astype(str) + " " + train_df['Review Text'].astype(str)
test_df['text_combined'] = test_df['Title'].astype(str) + " " + test_df['Review Text'].astype(str)

display(train_df[['Title', 'Review Text', 'text_combined']].head())

,Title,Review Text,text_combined
0,Versatile,I passed over this dress online thinking i'd n...,Versatile I passed over this dress online thin...
1,"Such a unique, flattering swimsuit!",I am so excited about this swimsuit. i have ne...,"Such a unique, flattering swimsuit! I am so ex..."
2,"The perfect skirt for all year, every year.","To start: i'm 135 lbs, 5'7"", 34c, 28 jeans, si...","The perfect skirt for all year, every year. To..."
3,Love this blouse,I really like this blouse a lot. very very eas...,Love this blouse I really like this blouse a l...
4,So crazy comfortable,I haven't worn jeans in a year because i felt ...,So crazy comfortable I haven't worn jeans in a...

In [47]:
# =========================
# 5. BASIC TEXT CLEANING
# =========================

import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

train_df['text_clean'] = train_df['text_combined'].apply(clean_text)
test_df['text_clean'] = test_df['text_combined'].apply(clean_text)

display(train_df[['text_combined', 'text_clean']].head())

,text_combined,text_clean
0,Versatile I passed over this dress online thin...,versatile i passed over this dress online thin...
1,"Such a unique, flattering swimsuit! I am so ex...",such a unique flattering swimsuit i am so exci...
2,"The perfect skirt for all year, every year. To...",the perfect skirt for all year every year to s...
3,Love this blouse I really like this blouse a l...,love this blouse i really like this blouse a l...
4,So crazy comfortable I haven't worn jeans in a...,so crazy comfortable i haven t worn jeans in a...

In [48]:
# =========================
# 6. FINAL VALIDATION
# =========================

print("Null count in train_df:", train_df.isnull().sum().sum())
print("Null count in test_df:", test_df.isnull().sum().sum())

print("\nSample cleaned text:")
print(train_df['text_clean'].head())

print("\nRecommended IND unique values:")
print(sorted(train_df['Recommended IND'].unique()))

print("\nRating unique values:")
print(sorted(train_df['Rating'].unique()))

Null count in train_df: 36
Null count in test_df: 6

Sample cleaned text:
0    versatile i passed over this dress online thin...
1    such a unique flattering swimsuit i am so exci...
2    the perfect skirt for all year every year to s...
3    love this blouse i really like this blouse a l...
4    so crazy comfortable i haven t worn jeans in a...
Name: text_clean, dtype: object

Recommended IND unique values:
[np.int64(0), np.int64(1)]

Rating unique values:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [49]:
# =========================
# 7. DEFINE FEATURES (NO RATING)
# =========================

# Only use cleaned text for the baseline/improved text model
X = train_df['text_clean']
y = train_df['Recommended IND']

# test set input
X_test_final = test_df['text_clean']

print("X shape:", X.shape)
print("y shape:", y.shape)
print("\ny distribution:")
print(y.value_counts(normalize=True))

X shape: (18788,)
y shape: (18788,)

y distribution:
Recommended IND
1    0.823238
0    0.176762
Name: proportion, dtype: float64

In [50]:
# =========================
# 8. TRAIN / VALIDATION SPLIT
# =========================

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train shape:", X_train.shape)
print("X_val shape:", X_val.shape)

print("\ny_train distribution:")
print(y_train.value_counts(normalize=True))

print("\ny_val distribution:")
print(y_val.value_counts(normalize=True))

X_train shape: (15030,)
X_val shape: (3758,)

y_train distribution:
Recommended IND
1    0.82322
0    0.17678
Name: proportion, dtype: float64

y_val distribution:
Recommended IND
1    0.82331
0    0.17669
Name: proportion, dtype: float64

In [52]:
# =========================
# 9. BASELINE MODEL: NAIVE BAYES
# =========================

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

nb_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(
        max_features=5000,
        ngram_range=(1, 2),
        stop_words='english'
    )),
    ('model', MultinomialNB())
])

nb_pipeline.fit(X_train, y_train)
y_val_pred_nb = nb_pipeline.predict(X_val)

In [53]:
# =========================
# 10. EVALUATE NAIVE BAYES
# =========================

from sklearn.metrics import f1_score, classification_report

f1_nb = f1_score(y_val, y_val_pred_nb, average='weighted')

print("Naive Bayes Weighted F1-score:", f1_nb)
print("\nNaive Bayes Classification Report:")
print(classification_report(y_val, y_val_pred_nb))

Naive Bayes Weighted F1-score: 0.8711895817596894

Naive Bayes Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.42      0.57       664
           1       0.89      0.99      0.94      3094

    accuracy                           0.89      3758
   macro avg       0.89      0.70      0.75      3758
weighted avg       0.89      0.89      0.87      3758

In [54]:
# =========================
# 11. LOGISTIC REGRESSION
# =========================

from sklearn.linear_model import LogisticRegression

lr_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(
        max_features=5000,
        ngram_range=(1, 2),
        stop_words='english'
    )),
    ('model', LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])

lr_pipeline.fit(X_train, y_train)
y_val_pred_lr = lr_pipeline.predict(X_val)

In [55]:
# =========================
# 12. EVALUATE LOGISTIC REGRESSION
# =========================

f1_lr = f1_score(y_val, y_val_pred_lr, average='weighted')

print("Logistic Regression Weighted F1-score:", f1_lr)
print("\nLogistic Regression Classification Report:")
print(classification_report(y_val, y_val_pred_lr))

Logistic Regression Weighted F1-score: 0.8918448103325801

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.54      0.66       664
           1       0.91      0.98      0.94      3094

    accuracy                           0.90      3758
   macro avg       0.88      0.76      0.80      3758
weighted avg       0.90      0.90      0.89      3758

In [66]:
# =========================
# 13. IMPROVED MODEL: TUNED BALANCED LOGISTIC REGRESSION
# =========================

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

balanced_lr_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(
        max_features=20000,          # more vocabulary
        ngram_range=(1, 3),          # add trigrams
        min_df=2,
        max_df=0.95,
        sublinear_tf=True,           # often helps text classification
        strip_accents='unicode',
        stop_words='english'
    )),
    ('model', LogisticRegression(
        max_iter=4000,
        C=3.0,                       # slightly weaker regularization
        class_weight='balanced',
        solver='liblinear',          # often strong for sparse text
        random_state=42
    ))
])

balanced_lr_pipeline.fit(X_train, y_train)
y_val_pred_balanced_lr = balanced_lr_pipeline.predict(X_val)

In [67]:
# =========================
# 14. EVALUATE IMPROVED LOGISTIC REGRESSION
# =========================

f1_balanced_lr = f1_score(y_val, y_val_pred_balanced_lr, average='weighted')

print("Balanced Logistic Regression Weighted F1-score:", f1_balanced_lr)
print("\nBalanced Logistic Regression Classification Report:")
print(classification_report(y_val, y_val_pred_balanced_lr))

Balanced Logistic Regression Weighted F1-score: 0.9009870942681876

Balanced Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.79      0.73       664
           1       0.95      0.92      0.94      3094

    accuracy                           0.90      3758
   macro avg       0.82      0.86      0.84      3758
weighted avg       0.91      0.90      0.90      3758

In [68]:
# =========================
# 15. MODEL COMPARISON
# =========================

print("Naive Bayes F1:", f1_nb)
print("Logistic Regression F1:", f1_lr)
print("Balanced Logistic Regression F1:", f1_balanced_lr)

Naive Bayes F1: 0.8711895817596894
Logistic Regression F1: 0.8918448103325801
Balanced Logistic Regression F1: 0.9009870942681876

In [69]:
# =========================
# 16. TASK 1 SCORE CALCULATION
# =========================

best_f1 = max(f1_nb, f1_lr, f1_balanced_lr)
task1_score = min(25, 25 * max(0, (best_f1 - 0.60) / 0.30))

print("Best validation F1-score:", best_f1)
print("Estimated Task 1 score:", task1_score)

Best validation F1-score: 0.9009870942681876
Estimated Task 1 score: 25

In [70]:
# =========================
# 17. SELECT BEST MODEL
# =========================

model_scores = {
    'Naive Bayes': f1_nb,
    'Logistic Regression': f1_lr,
    'Balanced Logistic Regression': f1_balanced_lr
}

best_model_name = max(model_scores, key=model_scores.get)

if best_model_name == 'Naive Bayes':
    best_pipeline = nb_pipeline
elif best_model_name == 'Logistic Regression':
    best_pipeline = lr_pipeline
else:
    best_pipeline = balanced_lr_pipeline

print("Best model selected:", best_model_name)
print("Best model F1:", model_scores[best_model_name])

Best model selected: Balanced Logistic Regression
Best model F1: 0.9009870942681876

In [71]:
# =========================
# 18. CONFUSION MATRIX
# =========================

from sklearn.metrics import confusion_matrix

best_pipeline.fit(X_train, y_train)
y_val_pred_best = best_pipeline.predict(X_val)

cm = confusion_matrix(y_val, y_val_pred_best)

cm_df = pd.DataFrame(
    cm,
    index=['Actual 0', 'Actual 1'],
    columns=['Predicted 0', 'Predicted 1']
)

print(cm_df)

          Predicted 0  Predicted 1
Actual 0          526          138
Actual 1          245         2849

In [62]:
# =========================
# 19. CROSS-VALIDATION
# =========================

from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    best_pipeline,
    X,
    y,
    cv=5,
    scoring='f1_weighted'
)

print("Cross-validation F1 scores:", cv_scores)
print("Mean cross-validation F1:", cv_scores.mean())
print("Std cross-validation F1:", cv_scores.std())

Cross-validation F1 scores: [0.89578105 0.89880078 0.89191785 0.89617029 0.89621716]
Mean cross-validation F1: 0.895777425717147
Std cross-validation F1: 0.002208379231077583

In [72]:
# =========================
# 20. RETRAIN BEST MODEL ON FULL TRAINING DATA
# =========================

best_pipeline.fit(X, y)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_df=0.95, max_features=20000, min_df=2,
                                 ngram_range=(1, 3), stop_words='english',
                                 strip_accents='unicode', sublinear_tf=True)),
                ('model',
                 LogisticRegression(C=3.0, class_weight='balanced',
                                    max_iter=4000, random_state=42,
                                    solver='liblinear'))])

In [73]:
# =========================
# 21. PREDICT TEST SET
# =========================

test_predictions = best_pipeline.predict(X_test_final)

print(test_predictions[:10])
print("Number of predictions:", len(test_predictions))

[1 1 1 0 1 1 0 1 1 1]
Number of predictions: 4698

In [74]:
# =========================
# 22. SAVE TASK 1 PREDICTIONS
# =========================

task1_submission = pd.DataFrame({
    'Recommended IND': test_predictions
})

task1_submission.to_csv("task1_predictions.csv", index=False)

display(task1_submission.head())
print("Saved file: task1_predictions.csv")

   Recommended IND
0                1
1                1
2                1
3                0
4                1

Saved file: task1_predictions.csv

TASK2

In [75]:
# =========================
# 24. TASK 2: DEFINE FEATURES AND TARGET
# =========================

# Baseline: use cleaned text only
X2 = train_df['text_clean']
y2 = train_df['Rating']

# Test set input
X2_test_final = test_df['text_clean']

print("X2 shape:", X2.shape)
print("y2 shape:", y2.shape)

print("\nRating distribution:")
print(y2.value_counts().sort_index())

X2 shape: (18788,)
y2 shape: (18788,)

Rating distribution:
Rating
1      689
2     1248
3     2251
4     4060
5    10540
Name: count, dtype: int64

In [76]:
# =========================
# 25. TASK 2: TRAIN / VALIDATION SPLIT
# =========================

from sklearn.model_selection import train_test_split

X2_train, X2_val, y2_train, y2_val = train_test_split(
    X2,
    y2,
    test_size=0.2,
    random_state=42,
    stratify=y2
)

print("X2_train shape:", X2_train.shape)
print("X2_val shape:", X2_val.shape)

print("\ny2_train distribution:")
print(y2_train.value_counts(normalize=True).sort_index())

print("\ny2_val distribution:")
print(y2_val.value_counts(normalize=True).sort_index())

X2_train shape: (15030,)
X2_val shape: (3758,)

y2_train distribution:
Rating
1    0.036660
2    0.066401
3    0.119827
4    0.216101
5    0.561011
Name: proportion, dtype: float64

y2_val distribution:
Rating
1    0.036722
2    0.066525
3    0.119745
4    0.216072
5    0.560937
Name: proportion, dtype: float64

In [77]:
# =========================
# 26. TASK 2 BASELINE: NAIVE BAYES
# =========================

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

nb_pipeline_task2 = Pipeline([
    ('tfidf', TfidfVectorizer(
        max_features=10000,
        ngram_range=(1, 2),
        stop_words='english'
    )),
    ('model', MultinomialNB())
])

nb_pipeline_task2.fit(X2_train, y2_train)
y2_val_pred_nb = nb_pipeline_task2.predict(X2_val)

In [78]:
# =========================
# 27. TASK 2 EVALUATE: NAIVE BAYES
# =========================

from sklearn.metrics import accuracy_score, classification_report

acc_nb_task2 = accuracy_score(y2_val, y2_val_pred_nb)

print("Task 2 Naive Bayes Accuracy:", acc_nb_task2)
print("\nTask 2 Naive Bayes Classification Report:")
print(classification_report(y2_val, y2_val_pred_nb))

Task 2 Naive Bayes Accuracy: 0.6027142096860032

Task 2 Naive Bayes Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       138
           2       0.50      0.01      0.02       250
           3       0.36      0.16      0.22       450
           4       0.37      0.12      0.18       812
           5       0.64      0.99      0.78      2108

    accuracy                           0.60      3758
   macro avg       0.37      0.26      0.24      3758
weighted avg       0.51      0.60      0.50      3758

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [79]:
# =========================
# 28. TASK 2 MODEL: LOGISTIC REGRESSION
# =========================

from sklearn.linear_model import LogisticRegression

lr_pipeline_task2 = Pipeline([
    ('tfidf', TfidfVectorizer(
        max_features=15000,
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.95,
        sublinear_tf=True,
        stop_words='english'
    )),
    ('model', LogisticRegression(
        max_iter=3000,
        C=2.0,
        multi_class='auto',
        random_state=42
    ))
])

lr_pipeline_task2.fit(X2_train, y2_train)
y2_val_pred_lr = lr_pipeline_task2.predict(X2_val)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [80]:
# =========================
# 29. TASK 2 EVALUATE: LOGISTIC REGRESSION
# =========================

acc_lr_task2 = accuracy_score(y2_val, y2_val_pred_lr)

print("Task 2 Logistic Regression Accuracy:", acc_lr_task2)
print("\nTask 2 Logistic Regression Classification Report:")
print(classification_report(y2_val, y2_val_pred_lr))

Task 2 Logistic Regression Accuracy: 0.6583288983501863

Task 2 Logistic Regression Classification Report:
              precision    recall  f1-score   support

           1       0.51      0.14      0.23       138
           2       0.36      0.26      0.30       250
           3       0.42      0.37      0.39       450
           4       0.47      0.35      0.40       812
           5       0.76      0.92      0.83      2108

    accuracy                           0.66      3758
   macro avg       0.51      0.41      0.43      3758
weighted avg       0.62      0.66      0.63      3758

In [81]:
# =========================
# 30. TASK 2 IMPROVED MODEL: TUNED LOGISTIC REGRESSION
# =========================

tuned_lr_pipeline_task2 = Pipeline([
    ('tfidf', TfidfVectorizer(
        max_features=25000,
        ngram_range=(1, 3),
        min_df=2,
        max_df=0.95,
        sublinear_tf=True,
        strip_accents='unicode',
        stop_words='english'
    )),
    ('model', LogisticRegression(
        max_iter=5000,
        C=3.0,
        solver='liblinear',
        random_state=42
    ))
])

tuned_lr_pipeline_task2.fit(X2_train, y2_train)
y2_val_pred_tuned_lr = tuned_lr_pipeline_task2.predict(X2_val)

In [82]:
# =========================
# 31. TASK 2 EVALUATE: TUNED LOGISTIC REGRESSION
# =========================

acc_tuned_lr_task2 = accuracy_score(y2_val, y2_val_pred_tuned_lr)

print("Task 2 Tuned Logistic Regression Accuracy:", acc_tuned_lr_task2)
print("\nTask 2 Tuned Logistic Regression Classification Report:")
print(classification_report(y2_val, y2_val_pred_tuned_lr))

Task 2 Tuned Logistic Regression Accuracy: 0.6532730175625333

Task 2 Tuned Logistic Regression Classification Report:
              precision    recall  f1-score   support

           1       0.47      0.14      0.21       138
           2       0.33      0.20      0.25       250
           3       0.42      0.36      0.39       450
           4       0.47      0.33      0.39       812
           5       0.75      0.93      0.83      2108

    accuracy                           0.65      3758
   macro avg       0.49      0.39      0.41      3758
weighted avg       0.61      0.65      0.62      3758

In [83]:
# =========================
# 32. TASK 2 MODEL COMPARISON
# =========================

print("Naive Bayes Accuracy:", acc_nb_task2)
print("Logistic Regression Accuracy:", acc_lr_task2)
print("Tuned Logistic Regression Accuracy:", acc_tuned_lr_task2)

Naive Bayes Accuracy: 0.6027142096860032
Logistic Regression Accuracy: 0.6583288983501863
Tuned Logistic Regression Accuracy: 0.6532730175625333

In [84]:
# =========================
# 33. TASK 2 SCORE CALCULATION
# =========================

best_acc_task2 = max(acc_nb_task2, acc_lr_task2, acc_tuned_lr_task2)
task2_score = min(25, 25 * max(0, (best_acc_task2 - 0.40) / 0.20))

print("Best validation accuracy:", best_acc_task2)
print("Estimated Task 2 score:", task2_score)

Best validation accuracy: 0.6583288983501863
Estimated Task 2 score: 25

In [85]:
# =========================
# 34. SELECT BEST TASK 2 MODEL
# =========================

task2_model_scores = {
    'Naive Bayes': acc_nb_task2,
    'Logistic Regression': acc_lr_task2,
    'Tuned Logistic Regression': acc_tuned_lr_task2
}

best_model_name_task2 = max(task2_model_scores, key=task2_model_scores.get)

if best_model_name_task2 == 'Naive Bayes':
    best_pipeline_task2 = nb_pipeline_task2
elif best_model_name_task2 == 'Logistic Regression':
    best_pipeline_task2 = lr_pipeline_task2
else:
    best_pipeline_task2 = tuned_lr_pipeline_task2

print("Best Task 2 model selected:", best_model_name_task2)
print("Best Task 2 accuracy:", task2_model_scores[best_model_name_task2])

Best Task 2 model selected: Logistic Regression
Best Task 2 accuracy: 0.6583288983501863

In [86]:
# =========================
# 35. TASK 2 CONFUSION MATRIX
# =========================

from sklearn.metrics import confusion_matrix
import pandas as pd

best_pipeline_task2.fit(X2_train, y2_train)
y2_val_pred_best = best_pipeline_task2.predict(X2_val)

cm_task2 = confusion_matrix(y2_val, y2_val_pred_best, labels=[1, 2, 3, 4, 5])

cm_task2_df = pd.DataFrame(
    cm_task2,
    index=['Actual 1', 'Actual 2', 'Actual 3', 'Actual 4', 'Actual 5'],
    columns=['Pred 1', 'Pred 2', 'Pred 3', 'Pred 4', 'Pred 5']
)

print(cm_task2_df)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

          Pred 1  Pred 2  Pred 3  Pred 4  Pred 5
Actual 1      20      41      37      15      25
Actual 2      10      64      97      36      43
Actual 3       9      50     166     128      97
Actual 4       0      17      71     285     439
Actual 5       0       6      26     137    1939

In [87]:
# =========================
# 36. TASK 2 CROSS-VALIDATION
# =========================

from sklearn.model_selection import cross_val_score

cv_scores_task2 = cross_val_score(
    best_pipeline_task2,
    X2,
    y2,
    cv=5,
    scoring='accuracy'
)

print("Task 2 cross-validation accuracy scores:", cv_scores_task2)
print("Mean CV accuracy:", cv_scores_task2.mean())
print("Std CV accuracy:", cv_scores_task2.std())

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Task 2 cross-validation accuracy scores: [0.63730708 0.65034593 0.64129856 0.64865584 0.64333245]
Mean CV accuracy: 0.644187971702423
Std CV accuracy: 0.004781414106383864

In [88]:
# =========================
# 37. RETRAIN BEST TASK 2 MODEL ON FULL DATA
# =========================

best_pipeline_task2.fit(X2, y2)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_df=0.95, max_features=15000, min_df=2,
                                 ngram_range=(1, 2), stop_words='english',
                                 sublinear_tf=True)),
                ('model',
                 LogisticRegression(C=2.0, max_iter=3000, multi_class='auto',
                                    random_state=42))])

In [89]:
# =========================
# 38. PREDICT TASK 2 TEST SET
# =========================

task2_test_predictions = best_pipeline_task2.predict(X2_test_final)

print(task2_test_predictions[:10])
print("Number of predictions:", len(task2_test_predictions))

[5 5 5 3 5 4 3 4 5 5]
Number of predictions: 4698

In [90]:
# =========================
# 39. SAVE TASK 2 PREDICTIONS
# =========================

task2_submission = pd.DataFrame({
    'Rating': task2_test_predictions.astype(int)
})

task2_submission.to_csv("task2_predictions.csv", index=False)

display(task2_submission.head())
print("Saved file: task2_predictions.csv")

   Rating
0       5
1       5
2       5
3       3
4       5

Saved file: task2_predictions.csv